apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: infra-repo 
  title: Infra repo 
  description: Setup git repository for manage and providing Infrastructure
  tags:
    - terraform 
    - terragrunt 

spec:
  type: IaC 
  parameters:
    - title: Project config 
      required:
        - project_name
        - aws_region
        - aws_access_key
        - aws_secret_access_key
      properties:
        project_name:
          title: Project Name
          type: string
        aws_access_key:
          title: AWS Access Key 
          type: string
          ui:field: Secret
        aws_secret_access_key:
          title: AWS Access Secret Key 
          type: string
          ui:field: Secret
        aws_region:
          title: AWS region 
          type: string
          default: us-east-1
          enum:
            - us-east-1
            - eu-west-2
          enumNames:
            - US East (N. Virginia)
            - Europe (London)


    - title: Repo setup
      required:
        - repoUrl 
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

    - title: Enviornment setup 
      required:
        - EnvName
      properties:
        EnvName:
          type: array
          title: A list of environment
          minItems: 0
          ui:options:
            addable: true
            orderable: true
            removable: true
          items: 
            type: string
            default: dev

  steps:
    - id: terraform_code 
      name: Fetch terraform code 
      action: fetch:template
      each: ${{parameters.EnvName}} 
      input:
        url: ./content
        targetPath: ./${{ each.value }}
        values: 
          project_name: ${{ parameters.project_name }}
          aws_region: ${{ parameters.aws_region }}
          env: ${{ each.value }}

    - id: github_action_code 
      name: Fetch action 
      action: fetch:template
      input:
        url: ./action
        targetPath: ./.github/workflows

    - id: catatlog_code 
      name: Fetch catalog 
      action: fetch:template
      input:
        url: ./catalog
        targetPath: ./
        values:  
          project_name: ${{ parameters.project_name }}

    - id: show_workspace
      name: Show workspace files
      action: debug:log
      input:
        listWorkspace: true

    - id: terraform_public
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: IaC for  ${{ parameters.project_name }}
        repoUrl: ${{ parameters.repoUrl }}
        gitCommitMessage: "[ADDED] webhost terraform stack" 
        branch: master
        secrets:
          AWS_ACCESS_KEY_ID:  ${{ parameters.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ parameters.aws_secret_access_key }}
        
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['terraform_public'].output.repoContentsUrl }} 
        catalogInfoPath: /catalog-info.yaml

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Code update 
        url: ${{ steps['terraform_public'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
