# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "ap-northeast-1"
  default_tags {
    tags = {
      Environment   = "prod"
      Owner         = "terraform"
      Project       = "kyozo"
      Orgranization = "mohara"
      Automate      = "true"
    }
  }
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}


data "aws_caller_identity" "current" {}
