# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "prod-kyozo-terraform-state"
    dynamodb_table = "dynamo-db-terraform-state-lock"
    key            = "prod-state/flutter-app-state.tfsate"
    region         = "ap-northeast-1"
  }
}
